#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain
print_info () {
    local subdomain="$1"
    local domain="$2"
    dig_output=$(dig "$subdomain.$domain" +short)
    if [[ -n "$dig_output" ]]; then
	    record_type="A"
	    destination="$dig_output"
	    echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
	    echo "No information found for subdomain $subdomain"
    fi
}

if [ "$#" -eq 2 ]; then
    print_info "$2" "$1"
else
    print_info "www" "$1"
    print_info "lb-01" "$1"
    print_info "web-01" "$1"
    print_info "web-02" "$1"
fi
