#!/usr/bin/env bash
#script that displays The content of the current directory in list format
for file in *; do
    if [ -f "$file" ] && [ ! -d "$file" ] && [[ "$file" == *-* ]]; then
       echo "${file#*-}"
    fi
done
