#!/usr/bin/env bash
# Check if correct number of arguments is provided

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path_to_file=$1
server_ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$server_ip":~/

if [ $? -eq 0 ]; then
    echo "File transferred successfuly."
else
    echo "Error occurred during file transfer."
fi
