#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get install -y nginx

# Ensure nginx is listening on port 80
sed -i 's/^\(.*listen\s\+\)80\(.*\)$/\180\2' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# Create a simple HTML file with "Hello World!"
echo "Hello World!" > /usr/share/nginx/html/index.html
