#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to add a custom Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '/server_name _;/a \\n\t# Add custom header\n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo systemctl restart nginx
