#!/usr/bin/env bash
# This script configures a new Ubuntu machine to serve as an HAProxy load balancer
sudo apt-get update
sudo apt-get install -y haproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [451122]-web-01:80 check
    server web-02 [451122]-web-02:80 check
EOF

sudo systemctl restart haproxy
sudo systemctl status haproxy
