#!/usr/bin/env bash

# This script stops, modifies, and restarts Nginx to listen on port 80

# Stop Nginx service
service nginx stop

# Modify Nginx configuration to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start
