#!/usr/bin/env bash

# This script stops, modifies, and restarts Nginx to listen on port 80

# Stop Nginx service
service nginx stop

# Modify Nginx configuration to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start

# Check if Nginx is running and listening on port 80
nc -z localhost 80
nginx_status=$?

# Validate Nginx status and HTTp response
if [ &nginx_status -eq 0 ]; then
	echo "Nginx is running and listening on port 80."
	# Send an HTTP request to port 80 and check the response code
	http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
	if [ $http_status -eq 200 ]; then
		echo "Nginx returned HTTP 200 OK on port 80."
		exit 0
	else
		echo "Nginx did not return HTTP 200 OK on port 80."
		exit 1
	fi
else
	echo "Nginx is not running or not listening on port 80."
	exit 1
fi
