#!/usr/bin/env bash
# This script stops, modifies, and restarts Nginx to listen on port 80
service nginx stop
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx start
curl -s 0:80 > /dev/null
service nginx status | grep -q "not running" && echo " * nginx is not running"
