#!/usr/bin/env bash

# This script stops, modifies, and restarts Nginx to listen on port 80

echo "nginx is not running"
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx start
