#!/usr/bin/env bash
#This script configures DNS resolution for localhost and facebook.com

#Before running the script
echo "Before running the script:"
ping localhost
ping facebook.com

#Update localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

#Update facebook.com to resolve to 8.8.8.8
sudo sed -i 's/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/8.8.8.8/g' /etc/hosts

#After running the script
echo -e "\nAfter running the script:"
ping localhost
ping facebook.com
