#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.

cp /etc/hosts /tmp/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' /tmp/hosts.new
sed -i '2i8.8.8.8 facebook.com' /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts
