#!/usr/bin/env bash
#This script displays all active IPv4 IPs on the machine

#Use hostname command to get the local IP address
local_ip=$(hostname -I | cut -d' ' -f1)

#Use curl to get the external IP address
external_ip=$(curl -s ifconfig.me)

#Display the IP
echo "$local_ip"
echo "$external_ip"
